# Ralph configuration — generated by `ralph init`. Edit freely; re-running
# `ralph init` will not overwrite this file.

# Commands Ralph runs locally before opening a PR. Empty string means
# "skip" (or, for INSTALL_CMD, the value the prompt-base will ask Claude
# to figure out at runtime).
INSTALL_CMD=""
TEST_CMD=""
LINT_CMD=""

# Branches. Autodetected from `origin/HEAD` and `git branch -a`.
MAIN_BRANCH="main"
DEV_BRANCH="main"
PR_TARGET="main"

# PR merge behavior.
MERGE_STRATEGY="squash"
AUTO_MERGE="true"
MERGE_POLL_INTERVAL=30
MERGE_POLL_MAX=40
